# Generated by Django 2.1.5 on 2019-11-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_Details',
            },
        ),
        migrations.CreateModel(
            name='Travel_Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=50)),
                ('Image1', models.ImageField(upload_to='img/images')),
                ('Image2', models.ImageField(upload_to='img/images')),
                ('Image3', models.ImageField(upload_to='img/images')),
                ('Itenary', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Price', models.IntegerField(default=None)),
                ('City', models.CharField(max_length=100)),
                ('Suitable_Month', models.CharField(max_length=100)),
                ('Suitable_for', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Travel_Packages',
            },
        ),
        migrations.CreateModel(
            name='User_Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('User_id', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Travelling_Date', models.CharField(max_length=100)),
                ('travelling_persons', models.IntegerField(default=None)),
                ('Review', models.CharField(max_length=5000)),
                ('Rating', models.IntegerField(default=None)),
                ('Group_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User_Bookings',
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Dob', models.CharField(default=None, max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.IntegerField(default=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
    ]
