# Generated by Django 2.1.5 on 2019-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_packages',
            name='Desc',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
