# Generated by Django 2.1.5 on 2019-11-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0002_travel_packages_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_packages',
            name='Desc',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='travel_packages',
            name='Duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travel_packages',
            name='Itenary',
            field=models.CharField(max_length=10000),
        ),
    ]
