# Generated by Django 2.1.5 on 2019-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0004_auto_20191118_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=50)),
                ('User_id', models.CharField(max_length=50)),
                ('Review', models.CharField(max_length=5000)),
                ('Rating', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.RenameField(
            model_name='user_bookings',
            old_name='Travelling_Date',
            new_name='Travelling_Month',
        ),
        migrations.RemoveField(
            model_name='user_bookings',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='user_bookings',
            name='Review',
        ),
    ]
