# Generated by Django 2.1.5 on 2019-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0005_auto_20191119_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bookings',
            name='PackageAmount',
            field=models.IntegerField(default=0),
        ),
    ]
