# Generated by Django 2.1.5 on 2019-11-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0006_user_bookings_packageamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Rating',
            new_name='Ratings',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='Reviews',
        ),
    ]
