# Generated by Django 2.1.5 on 2019-11-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0007_auto_20191120_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='User_Review',
        ),
        migrations.AlterModelTable(
            name='user_review',
            table='User_Review',
        ),
    ]
