# Generated by Django 2.1.5 on 2019-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0008_auto_20191120_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='productid',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
