# Generated by Django 2.1.5 on 2019-11-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0010_auto_20191120_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='month',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
