# Generated by Django 2.1.5 on 2019-11-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0011_user_review_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_packages',
            old_name='Suitable_City',
            new_name='City',
        ),
    ]
