# Generated by Django 2.1.5 on 2019-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDecisionTreeBasedTourism', '0012_auto_20191121_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bookings',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
